name: pphelper
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_easyrefresh: ^2.2.1
  dio: ^4.0.1
  flutter_screenutil: 5.3.1
  flutter_staggered_grid_view: 0.6.1
  flutter_html: ^2.2.1
  shared_preferences: 2.0.13
  fluttertoast: 8.0.9
  image_picker: 0.8.4+11
  flutter_picker: 2.0.3
  bubble: 1.2.1
  font_awesome_flutter: 10.1.0
  card_swiper: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/1.0x/images/empty.png
    - assets/1.0x/images/wx.png
    - assets/1.0x/images/alipay.png
    - assets/1.0x/images/wallet.png
  uses-material-design: true

